### ISSUE TITLE
Report crash when tracing fails

### ISSUE THREAD

**Issue by v-p-b** [intel/kernel-fuzzer-for-xen-project#11]
I managed to catch exceptions on Windows without providing the KPGD address to the fuzzer with #10. This is probably because the exception handler address is still mapped to the VA space of the user-mode process.

I had to tweak my test program though: instead of doing a `call` to 0x0, now I trigger a write access violation. This was important, because in the original setup, the tracer failed to follow the branch to the unmapped address. This results in a tracing error without registering a crash.

I think the correct behavior would be to set the crash flag in these cases, since trying to branch to an invalid address is a scenario worth reporting.

**Comment by tklengyel** [comment]
Address in https://github.com/intel/kernel-fuzzer-for-xen-project/commit/6e922b81504f27d014135670947151ce9530167e
