### ISSUE TITLE
[FAQ request] How my target runs exactly? What rules are there for harnessing?

### ISSUE THREAD

**Issue by fuzzah** [intel/kernel-fuzzer-for-xen-project#16]
I think FAQ lacks some technical info and rules for placing harness function (cpuid).
 
1.a) Does kfx make new VM fork every single harness-to-harness loop or does it manipulate registers to make such a loop (like WinAFL does)?
 
1.b) If new VM fork is made for each loop, I don't need to restore state, right?
 
2.a) Is it OK to add harness inside of tested function itself? I can't call my tested function directly (and harness it as in tutorial), because it's a callback function, so I don't even know all the places from which it's getting called. (i know i can also wrap the whole function inside of another one but i'm affraid to mess up when dealing with huge portions of code in complex systems)
 
2.b) What if I have multiple **return**s from such a function with harness inside? Do I just insert call to harness instead of each return statement? Or is it absolutely required to wrap my tested code as a function and put exactly two calls to harness?
 
3.a) Can I put harness calls in completely different modules? The first harness would be in module X, which receives data (e.g. from the procfs), the second harness call would be after the data have been parsed in module Y.
 
3.b) Can I put harness in both usemode binary and in kernel module? E.g. usermode application receives data from TCP socket, parses it somehow, then sends parsed result to kernel module (ioctl, procfs, etc.), where I expect my module to crash.
 
3.c) Same as in previous question, but what if data flows from kernel module to usermode application and I expect both module and app to crash? (both binary and module do some parsing and i'd like to catch bugs in both)
 
Thanks in advance!

**Comment by tklengyel** [comment]
> 1.a) Does kfx make new VM fork every single harness-to-harness loop or does it manipulate registers to make such a loop (like WinAFL does)?

kfx makes two forks from the VM, one where the "sink" functions are breakpointed, and then a fork form that VM: `parent -> sink VM -> fuzz VM`. Each iteration of the fuzzer resets the `fuzz VM` to the start state, throwing away any memory that was allocated to it and resetting its registers.

> 1.b) If new VM fork is made for each loop, I don't need to restore state, right?

The fork made for fuzzing is reset automatically, you don't have to do anything to restore it. You can specify to make new forks if you want to by using the `--refork <number>` flag. It should not be necessary, a reset is better, so this option is mainly just for debugging.

> 2.a) Is it OK to add harness inside of tested function itself?

Yes, the harness is safe to be placed anywhere.

> 2.b) What if I have multiple returns from such a function with harness inside? Do I just insert call to harness instead of each return statement? Or is it absolutely required to wrap my tested code as a function and put exactly two calls to harness?

You do need two harness calls. The first marks the start location of where the fuzzing will begin, the second marks where it ends. If any of the breakpointed "sink" locations execute between those two harness points, then that's reported as a crash to AFL.

> 3.a) Can I put harness calls in completely different modules?

Yes, as long as the normal execution always reaches the second harness. If the execution flow doesn't reach the second harness then the VM will run for a long time and AFL will timeout.

> 3.b) Can I put harness in both usemode binary and in kernel module?

Yes

> 3.c) Same as in previous question, but what if data flows from kernel module to usermode application and I expect both module and app to crash?

Yes, but to catch crashes in usermode you have to update the sinkpoints. Currently only pagefaults from userspace would be caught. If you want to catch other "signals" you would have to figure out which kernel function handles them and breakpoint those as well.

**Comment by fuzzah** [comment]
@tklengyel thank you.

> You do need two harness calls. The first marks the start location of where the fuzzing will begin, the second marks where it ends. If any of the breakpointed "sink" locations execute between those two harness points, then that's reported as a crash to AFL.

Please imagine a function like this:
```
int f(int x, int y)
{
	char *buf = kmalloc(10, GFP_KERNEL); // some memory allocation
	if (y == 0) {
		printk("[test] error: y == 0\n");
		kfree(buf);
		return -1;
	}
	if (x + y < 0) {
		printk("[test] error: x + y < 0\n");
		kfree(buf);
		return -2;
	}
	
	// some buf handling
	buf[0] = x % 10;
	buf[9] = (x + y) & 0xFF;
	
	kfree(buf);
	return x / y;
}
```

When adapting function like this to fuzzing I inserted calls to harness() before each return, so that second call to cpuid could be reached in any case. So the above code becomes
```
iint f(int x, int y)
{
	char *buf = kmalloc(10, GFP_KERNEL); // some memory allocation
	harness(); // first call
	if (y == 0) {
		printk("[test] error: y == 0\n");
		kfree(buf);
		harness(); // second call in case of y == 0
		return -1;
	}
	if (x + y < 0) {
		printk("[test] error: x + y < 0\n");
		kfree(buf);
		harness(); // second call in case of x + y < 0
		return -2;
	}
	
	// some buf handling
	buf[0] = x % 10;
	buf[9] = (x + y) & 0xFF;
	
	kfree(buf);
	harness(); // second call in other cases
	return x / y;
}
```
Will that work as intended?

**Comment by tklengyel** [comment]
LGTM
