### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by bamiaux** [intel/kernel-fuzzer-for-xen-project#17]
Hi, 

Thanks for this great project !

I have some issues with scaling properly, when using multiple connected AFL fuzzers.
Maybe you have some suggestions on how to reduce bottlenecks ?

On my test case, with a 4-core with HT (so 8 logical cores), and intel pt coverage

1 core =~1500 exec/s
4 core =~2500 exec/s

I tried to play with affinity and CPU pinning, but it doesn't significantly change the performance.
I know I should not expect linear scaling, but maybe there are xen/other knobs I can tweak to reduce the gap ?

**Comment by tklengyel** [comment]
That's not so surprising if you have HT enabled. You would see linear scaling of speed only if HT is disabled. With HT enabled some of your VMs may start sharing a core and slow down because of that. Try disabling HT.

**Comment by bamiaux** [comment]
Disabling HT does help a little, it's also much easier to reason about cpu, vcpu & pinning
But it is still slow imho. On a 2x10 cpu core, I also need to do
```
xl cpupool-numa-split
```
And put all cores from the second processor into an unused pool. It looks like (not properly verified) we need kfx & the controlled vm working in tandem on the same vcpu.
Rate limiting also does not significantly change results:
```
xl sched-credit2 -s -r=somevalue
```
It seems to me there is a lot of contention on syscalls, or vm reset.
Also, profiling it with ```perf top -g``` is noisy with lots of idle time inside xen code

**Comment by tklengyel** [comment]
@bamiaux You are in uncharted territory, especially when it comes to running kfx on machines with multiple NUMA cores :) In that case indeed it would help if the dom0 vcpu that kfx is using is on the same NUMA core as the VM's vcpu that is being monitored. Otherwise you might get a lot of cross-NUMA core messages. So beside having to do vCPU pinning you might also need to pin the kfx process inside dom0.

Overall it might actually be easier to do this with secondary control domains that you can do with when you compile Xen with XSM enabled, that way you don't have to run everything out of dom0.

**Comment by bamiaux** [comment]
Yes, having at least one control domain per numa node would be better. Maybe even one control domain per kfx could achieve better scaling, if it can reduce contention further.
I didn't know about XSM, are you talking about Xen Security Modules, which would enable xc API to be available on multiple domains, not just dom0 ?
Anyway, I'll look (a little) into it

**Comment by tklengyel** [comment]
> I didn't know about XSM, are you talking about Xen Security Modules, which would enable xc API to be available on multiple domains, not just dom0 ?

Correct, you just create a second domain and give it the permissions it needs to run kfx (or just run in permissive mode). It's like SELinux just for Xen. Then you can pin that secondary domain on the same NUMA node as its VMs will be that it uses for fuzzing. The documentation I wrote for XSM is now a bit dated but you can find it at https://wiki.xenproject.org/wiki/Xen_Security_Modules_:_XSM-FLASK

**Comment by tklengyel** [comment]
@bamiaux @andyhhp I just pushed a patch to the Xen submodule that was actually preventing multiple afl instances from running. So if you ran into afl stopping & complaining about the forkserver being possibly OOM, this fixes it. Just build xen from the submodule tagged on master.

**Comment by fuzzah** [comment]
> So if you ran into afl stopping & complaining about the forkserver being possibly OOM, this fixes it

@tklengyel hey, thanks for that! I was sure it was my local problem with my specific target
