### ISSUE TITLE
Saving and restoring setup state: Device model spawn failed

### ISSUE THREAD

**Issue by v-p-b** [intel/kernel-fuzzer-for-xen-project#21]
Saving and restoring already setup domains is a huge productivity boost, that as far as I remember worked great a couple months back. Now when I want to save/restore domains like this:

```
# xl save -p target_domain target_setup.sav
# xl destroy target_domain 
# xl restore -p target_setup.sav
```

... I get an error similar to the following:

```
Loading new save file target_setup.sav (new xl fmt info 0x3/0x0/1579)
 Savefile contains xl domain config in JSON format
Parsing config from <saved>
xc: info: Found x86 HVM domain from Xen 4.15
xc: info: Restoring domain
xc: info: Restore successful
xc: info: XenStore: mfn 0xfeffc, dom 0, evt 1
xc: info: Console: mfn 0xfefff, dom 0, evt 2
libxl: error: libxl_dm.c:3102:device_model_spawn_outcome: Domain 1:domain 1 device model: spawn failed (rc=-3)
libxl: error: libxl_dm.c:3318:device_model_postconfig_done: Domain 1:Post DM startup configs failed, rc=-3
libxl: error: libxl_create.c:1833:domcreate_devmodel_started: Domain 1:device model did not start: -3
libxl: error: libxl_aoutils.c:646:libxl__kill_xs_path: Device Model already exited
libxl: error: libxl_domain.c:1182:libxl__destroy_domid: Domain 1:Non-existant domain
libxl: error: libxl_domain.c:1136:domain_destroy_callback: Domain 1:Unable to destroy guest
libxl: error: libxl_domain.c:1063:domain_destroy_cb: Domain 1:Destruction of domain failed
```

How can I save/restore domains after `kfx --setup ...`?

**Comment by tklengyel** [comment]
You can check the QEMU error log in `/var/log/xen/`, that will tell you why it failed to start.

**Comment by tklengyel** [comment]
Interestingly with a Linux guest I can't even save the domain after it's paused with the `--setup` step but that's likely because the Linux save/restore routine actually requires cooperation from the guest, unlike a Windows guest. I guess that's because the Linux VM is paused in the kernel during inserting a kernel module and whatever injection routine the Xen toolstack uses to kick the guest into cooperating fails. /cc @andyhhp thoughts?

**Comment by v-p-b** [comment]
Looks like it's a QEMU bug in my case:

```
qemu-system-i386: -usbdevice tablet: '-usbdevice' is deprecated, please use '-device usb-...' instead                                                                                                                                         
char device redirected to /dev/pts/4 (label serial0)
xen_ram_alloc: do not alloc 7f000000 bytes of ram at 0 when runstate is INMIGRATE
xen_ram_alloc: do not alloc 1000000 bytes of ram at 7f000000 when runstate is INMIGRATE
xen_ram_alloc: do not alloc 10000 bytes of ram at 80000000 when runstate is INMIGRATE
xen_ram_alloc: do not alloc 40000 bytes of ram at 80040000 when runstate is INMIGRATE
VNC server running on 0.0.0.0:5900
Replacing a dummy mapcache entry for 000000007f000000 with 00000000f1000000
qemu-system-i386: Unknown savevm section or instance 'audio' 0. Make sure that your current VM setup matches your saved VM setup, including any hotplugged devices
qemu-system-i386: load of migration failed: Invalid argument
```

https://www.mail-archive.com/qemu-devel@nongnu.org/msg607905.html
https://wiki.qemu.org/Planning/4.0

**Comment by andyhhp** [comment]
@tklengyel Windows requires just as much cooperation as Linux.  Don't be fooled by the utter junk in libxc on this matter.

Cooperation is mandatory for:
* PV guests.  They need to understand that all their established pagetables, and the in-guest p2m has been rewritten for them across migration.  Also, the pointer to the shared_info page is stashed in a register and rewritten across migrate.
* PV drivers.  The original authors didn't plumb grant mappings into the logdirty bitmap, instead requiring the guest kernel (after all - cooperation was mandatory for PV guests when this was put together) to know that they needed to reply any content still in the ring, as it may or may not have been processed on the source side.

Work is ongoing upstream to develop guest transparent/unaware migration, which would lift the PV drivers restriction for HVM/PVH guests, but it still has a long way to go until it is ready.

**Comment by v-p-b** [comment]
So in summary this is not supported right now (and my memories are failing me, which is quite possible)? If so, I think you can close this issue/keep it as a feature request.
