### ISSUE TITLE
Performance monitoring

### ISSUE THREAD

**Issue by v-p-b** [intel/kernel-fuzzer-for-xen-project#23]
What is the recommended way to monitor the performance of the (physical) CPU's while running KF/x?

`top` in dom0 only sees the vCPU's of dom0.

As far as I can tell `xentop` can't provide meaningful information, because the (forked) domains (dis)appear too fast.

**Comment by tklengyel** [comment]
`xl top`

**Comment by tklengyel** [comment]
If `xentop` (or `xl top`) is not meaningful you can just keep an eye on the time spent running the vCPUs listed with `xl list`.

**Comment by v-p-b** [comment]
The mentioned commands work for the forked domain after it is [given a name](http://www.mimastech.com/2016/08/16/howto-rename-a-xen-vm-domain-using-xl-and-xm/) with `xl -vf rename DOMID SOMENAME`.
