### ISSUE TITLE
Documentation bugs: Xen installation

### ISSUE THREAD

**Issue by v-p-b** [intel/kernel-fuzzer-for-xen-project#3]
The README misses a command line redirection to update the GRUB config:

https://github.com/intel/kernel-fuzzer-for-xen-project/blame/master/README.md#L82

Also, following the steps the Xen systemd units don't get installed: 

```
# systemctl enable xen-init-dom0.service
Failed to enable unit: Unit file xen-init-dom0.service does not exist.
```

I'd appreciate some help on the latter one.

**Comment by v-p-b** [comment]
Re: networking

The `ifconfig` command is no longer available on recent Debian/Ubuntu installs (and the corresponding package is not among the listed dependencies). The `ifconfig` command can be replaced with:

```
ip a add 10.0.0.1/24 dev xenbr0 
ip link set xenbr0 up
```

**Comment by tklengyel** [comment]
Thanks, I was also missing the  `libsystemd-dev` package installation from the list, that's why the dom0 service wasn't getting installed. I'll update the README accordingly.

**Comment by v-p-b** [comment]
The GRUB command line redirection is missing again (merging error probably):

https://github.com/intel/kernel-fuzzer-for-xen-project/blame/master/README.md#L91
