### ISSUE TITLE
Unable to request new process from fork server (OOM?)

### ISSUE THREAD

**Issue by dgh05t** [intel/kernel-fuzzer-for-xen-project#32]
Hi,

When I test the fuzzer, sometimes the fuzzed process (kfx) returned directly, and AFL will show error `Unable to request new process from fork server (OOM?)`

but when I comment out the code sanity check of the first input file (https://github.com/intel/kernel-fuzzer-for-xen-project/blob/7a088025f95af76a5afecd4d3936c0fc7997b305/src/main.c#L394 to https://github.com/intel/kernel-fuzzer-for-xen-project/blob/7a088025f95af76a5afecd4d3936c0fc7997b305/src/main.c#L400) , the program goes well then.

It seems because when sanity check happens, AFL hasn't create the testcase .cur_input yet.

**Comment by tklengyel** [comment]
Thanks for looking into it, I've seen that happen from time to time. Usually just have to try again to get AFL up and running but perhaps waiting a bit in case the file doesn't exist yet and trying again would be more robust.

**Comment by tklengyel** [comment]
I've pushed https://github.com/intel/kernel-fuzzer-for-xen-project/commit/03e3a9744460391ecab38a8094b485b5429b6dfc that should skip this sanity check when running with AFL. Let me know if you still see the issue.

**Comment by dgh05t** [comment]
Yes, the issue is resolved now.
