### ISSUE TITLE
Too early input file read

### ISSUE THREAD

**Issue by v-p-b** [intel/kernel-fuzzer-for-xen-project#5]
When doing the dry run AFL first sets up and checks the fork server, and only creates the actual input file after this setup was successful. 

`kernel-fuzzer` exits early, before AFL shared memory initialization, if the input file cannot be opened:

https://github.com/intel/kernel-fuzzer-for-xen-project/blob/master/src/main.c#L260

I think this check could be simply moved after the `afl_setup()` call.

**Comment by tklengyel** [comment]
Yeap, looks like that would be better.
