### ISSUE TITLE
Reopen file for new input

### ISSUE THREAD

**Issue by v-p-b** [intel/kernel-fuzzer-for-xen-project#7]
Currently `get_input()` just keeps reading the same file descriptor, that can only supply finite amount of data (see #6). I think the harness should seek to position 0 on new input (and this is somehow confirmed by my tests), but I'm not quite sure how exactly Linux handles fd's when the underlying contents are overwritten.

**Comment by v-p-b** [comment]
Just created a small test and it shows that without reopening the file the contents will be presented to the program as they were when opened. Overwriting the file doesn't affect the output of read.

```c
#include<stdio.h>
#include<stdlib.h>
int main(){

        FILE* fd=fopen("test.dat","r");
        char* buf=(char*)malloc(4);;
        while(1){
          fread(buf,1,4,fd);
          printf("buf: %02x %02x %02x %02x\n", buf[0], buf[1], buf[2], buf[3]);
          getchar();
          fseek(fd,0,SEEK_SET);
        }
        return 0;
}

```

**Comment by tklengyel** [comment]
Hm I guess then we should be opening a fresh fd and closing it in get_input.
