### ISSUE TITLE
VM Network issue

### ISSUE THREAD

**Issue by kbh1860** [intel/kernel-fuzzer-for-xen-project#79]
Hello! I'm interested in your project, But there is some issue...

I finished to step 6, but the vm doesn't have network

i Try to add nameservers in  `/etc/netplan/02-xenbr0.yaml`,

`
root@b:~# cat /etc/netplan/02-xenbr0.yaml 
network:
  version: 2
  renderer: networkd
  bridges:
    xenbr0:
      dhcp4: no
      addresses: [ 192.168.2.200/24 ]
      gateway4: 192.168.1.1
      nameservers:
        addresses: [8.8.8.8]
`

like this, but vm can't connect to internet

And my environment like this

`
OS :  Ubuntu 20.04
network environment:

root@b:~# ifconfig
enp4s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.47  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::3f91:fee5:7668:56e4  prefixlen 64  scopeid 0x20<link>
        ether 04:7c:16:16:95:19  txqueuelen 1000  (Ethernet)
        RX packets 3142668  bytes 4723579072 (4.7 GB)
        RX errors 0  dropped 9  overruns 0  frame 0
        TX packets 803889  bytes 57822615 (57.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 29295  bytes 22806428 (22.8 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 29295  bytes 22806428 (22.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vif4.0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether fe:ff:ff:ff:ff:ff  txqueuelen 32  (Ethernet)
        RX packets 96  bytes 13446 (13.4 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2  bytes 260 (260.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlo1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 8c:b8:7e:96:c7:1f  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

xenbr0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.2.200  netmask 255.255.255.0  broadcast 192.168.2.255
        inet6 fe80::a852:f3ff:fe11:2204  prefixlen 64  scopeid 0x20<link>
        ether fe:ff:ff:ff:ff:ff  txqueuelen 1000  (Ethernet)
        RX packets 311  bytes 44592 (44.5 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 103  bytes 14821 (14.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
`

Lastly, I try to `iptables -t nat -A POSTROUTING -o enp4s0 -j MASQUERADE`, but that command can't help...

What can i do in like this situation?? Can you give me the advise??

**Comment by tklengyel** [comment]
Read the instructions more closely. If you are not setting up a DHCP server you manually have to set your dns configuration in the VM. If you are setting up the DHCP server, follow its instructions, like linked to in the README: https://computingforgeeks.com/install-and-configure-dnsmasq-on-ubuntu
