### ISSUE TITLE
VM network settings failed 

### ISSUE THREAD

**Issue by 5angjun** [intel/kernel-fuzzer-for-xen-project#80]
Hi, i'm sangjun who interested in Xen-fuzz.

Now, i'm settings fuzz evironment to use this project.

But, i stucked with VM network settings.

i follow this command. but in Vm machine, there is no network connected.

```
iptables -t nat -A POSTROUTING -o enp4s0 -j MASQUERADE
```

Can you tell more detail about network settings??

I would really appreciate it if you could write more kindly about vm network settings.

Thanks

**Comment by tklengyel** [comment]
Can you ping dom0? Can you ping outside network (like 8.8.8.8)?
If yes and yes, the issue is with your DNS setting in the VM.
If you can't ping outside the issue is with your routing and NAT setup.
If you can't ping dom0 the issue is with your bridge.

**Comment by 5angjun** [comment]
i cant ping ro dom0.😂😂

But i just follow the step 5. Setup networking.

I am weak in network environment settings, so I would appreciate it if you could kindly let me know step by step.


I was interested in this project, so I looked up all the explanation videos on YouTube, but I would be really sad if I got stuck in the environment settings and couldn't even try using it.

**Comment by tklengyel** [comment]
If you can't ping dom0 then your bridge in dom0 is not setup properly. What IP did you set for xenbr0? The VM needs to be configured to be on the same IP subnet the dom0 bridge is.

**Comment by 5angjun** [comment]
Hi there.

Thanks for very fast reply for my question.

To explain more specific how my envrionment setted. 

I re-installed ubuntu 20.04 and follow the Readme.md command and take a video to show the stucked problem.
https://youtu.be/r9UNe99b_uk

![Screenshot from 2023-11-01 11-38-06](https://github.com/intel/kernel-fuzzer-for-xen-project/assets/76202024/0b0f7867-b6c3-4fb9-948e-d4ac7cd55c4f)

What should i do in this problem?

Thanks

**Comment by tklengyel** [comment]
You eth0 interface in the VM has no IP configured. You need to manually set an IP for it on the 10.0.0.0/24 network and configure a valid DNS for it. Since you have a GUI just go to the network settings. Check https://www.freecodecamp.org/news/setting-a-static-ip-in-ubuntu-linux-ip-address-tutorial/ and go to the section "How to Set a Static IP Using the GUI"

**Comment by 5angjun** [comment]
Its done. Very Thansk😭😀😀
